# Generated by Django 2.2.8 on 2020-01-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_auto_20200122_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='due_on',
        ),
    ]
