# Generated by Django 2.2.8 on 2020-01-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_remove_borrowing_due_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
