# Generated by Django 2.2.8 on 2020-01-23 06:58

from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notification', tinymce.models.HTMLField()),
                ('user', models.ManyToManyField(blank=True, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
