# Generated by Django 2.2.8 on 2020-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
