# Generated by Django 2.2.8 on 2020-05-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0012_user_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('pick_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(default='1111-1-11')),
                ('renew_card', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
